[project]
name = "AnimalsProfitPlot"
version = "0.1.0"
description = "动物利润计算器"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
]

[tool.ruff]
"indent-width" = 2
"line-length" = 115
